### ISSUE TITLE
"Clarify when thinking / situation has changed", maintainer best practice

### ISSUE THREAD

**Issue by Beanow** [sourcecred/docs#8]
Tracking suggestion from https://github.com/sourcecred/docs/pull/1#discussion_r368151211

_I believe for context it's best to read :point_up: the above review comments. So I am only copying this excerpt:_

> @vsoch 
> The general idea is that you wouldn't want to say "OH sorry we don't need / want this anymore" but something more like "Our thinking has changed and we think this [other thing] might be a better strategy to pursue, would you be interested in helping with well scoped task]?

cc @decentralion @BrianLitwin

**Comment by vsoch** [comment]
okay I just added a paragraph for this under #9
