### ISSUE TITLE
Broken link on https://sourcecred.io/docs/concepts/grain/

### ISSUE THREAD

**Issue by bileschi** [sourcecred/docs#90]
The link on https://sourcecred.io/docs/concepts/grain/ with text "preview balances." points to "https://discourse.sourcecred.io/t/sourcecred-contributor-payouts/298." Looks like it should be "https://discourse.sourcecred.io/t/sourcecred-contributor-payouts/298" (without the period)

**Comment by decentralion** [comment]
Thanks for reporting and fixing!
